// Code generated by protoc-gen-go. DO NOT EDIT.
// source: first-grpc.proto

package first_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request param
type RequestParam struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestParam) Reset()         { *m = RequestParam{} }
func (m *RequestParam) String() string { return proto.CompactTextString(m) }
func (*RequestParam) ProtoMessage()    {}
func (*RequestParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_09af94091b285fd0, []int{0}
}

func (m *RequestParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestParam.Unmarshal(m, b)
}
func (m *RequestParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestParam.Marshal(b, m, deterministic)
}
func (m *RequestParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestParam.Merge(m, src)
}
func (m *RequestParam) XXX_Size() int {
	return xxx_messageInfo_RequestParam.Size(m)
}
func (m *RequestParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestParam.DiscardUnknown(m)
}

var xxx_messageInfo_RequestParam proto.InternalMessageInfo

func (m *RequestParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// The response message
type ReplyBody struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyBody) Reset()         { *m = ReplyBody{} }
func (m *ReplyBody) String() string { return proto.CompactTextString(m) }
func (*ReplyBody) ProtoMessage()    {}
func (*ReplyBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_09af94091b285fd0, []int{1}
}

func (m *ReplyBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBody.Unmarshal(m, b)
}
func (m *ReplyBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBody.Marshal(b, m, deterministic)
}
func (m *ReplyBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBody.Merge(m, src)
}
func (m *ReplyBody) XXX_Size() int {
	return xxx_messageInfo_ReplyBody.Size(m)
}
func (m *ReplyBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBody.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBody proto.InternalMessageInfo

func (m *ReplyBody) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplyBody) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestParam)(nil), "first_grpc.RequestParam")
	proto.RegisterType((*ReplyBody)(nil), "first_grpc.ReplyBody")
}

func init() {
	proto.RegisterFile("first-grpc.proto", fileDescriptor_09af94091b285fd0)
}

var fileDescriptor_09af94091b285fd0 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcb, 0x2c, 0x2a,
	0x2e, 0xd1, 0x4d, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x8b,
	0xc4, 0x83, 0x44, 0x94, 0x2c, 0xb8, 0x78, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x02, 0x12,
	0x8b, 0x12, 0x73, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0xb0,
	0x20, 0x84, 0xa3, 0x64, 0xc9, 0xc5, 0x19, 0x94, 0x5a, 0x90, 0x53, 0xe9, 0x94, 0x9f, 0x52, 0x09,
	0xd2, 0x96, 0x9c, 0x9f, 0x02, 0xd1, 0xc6, 0x1a, 0x04, 0x66, 0x0b, 0x49, 0x70, 0xb1, 0xe7, 0xa6,
	0x16, 0x17, 0x27, 0xa6, 0xc3, 0x34, 0xc2, 0xb8, 0x46, 0x5e, 0x5c, 0x9c, 0x6e, 0x20, 0x27, 0xb8,
	0x07, 0x05, 0x38, 0x0b, 0xd9, 0x72, 0x71, 0x84, 0xa4, 0x42, 0xd9, 0x12, 0x7a, 0x08, 0xa7, 0xe9,
	0x21, 0xbb, 0x4b, 0x4a, 0x14, 0x55, 0x06, 0x6a, 0xaf, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x4f, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x57, 0x2f, 0xf1, 0xe7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FirstGRPCClient is the client API for FirstGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FirstGRPCClient interface {
	// Sends Call
	TestGRPC(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*ReplyBody, error)
}

type firstGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstGRPCClient(cc grpc.ClientConnInterface) FirstGRPCClient {
	return &firstGRPCClient{cc}
}

func (c *firstGRPCClient) TestGRPC(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*ReplyBody, error) {
	out := new(ReplyBody)
	err := c.cc.Invoke(ctx, "/first_grpc.FirstGRPC/TestGRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstGRPCServer is the server API for FirstGRPC service.
type FirstGRPCServer interface {
	// Sends Call
	TestGRPC(context.Context, *RequestParam) (*ReplyBody, error)
}

// UnimplementedFirstGRPCServer can be embedded to have forward compatible implementations.
type UnimplementedFirstGRPCServer struct {
}

func (*UnimplementedFirstGRPCServer) TestGRPC(ctx context.Context, req *RequestParam) (*ReplyBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestGRPC not implemented")
}

func RegisterFirstGRPCServer(s *grpc.Server, srv FirstGRPCServer) {
	s.RegisterService(&_FirstGRPC_serviceDesc, srv)
}

func _FirstGRPC_TestGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstGRPCServer).TestGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/first_grpc.FirstGRPC/TestGRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstGRPCServer).TestGRPC(ctx, req.(*RequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _FirstGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "first_grpc.FirstGRPC",
	HandlerType: (*FirstGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestGRPC",
			Handler:    _FirstGRPC_TestGRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "first-grpc.proto",
}
